matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - uuid-dev
      env:
         - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - uuid-dev
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - uuid-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0"
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty
#          packages:
#            - clang-5.0
#            - uuid-dev
#      env:
#        - MATRIX_EVAL="CC=clang-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
language: c
dist: trusty
sudo: required
script:
  - export PATH="$PATH:${BUILD_PREFIX}/bin"
  - $CC --version
  - ./bootstrap.sh
  - ./configure
  - make
