matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
         - MATRIX_EVAL="CC=gcc-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-3.8"

before_install:
  - eval "${MATRIX_EVAL}"
language: c
script:
  - export PATH="$PATH:${BUILD_PREFIX}/bin"
  - ./bootstrap.sh
  - ./configure
  - make
