matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - iptables-dev
            - gcc-5
            - uuid-dev
            - linux-headers-generic
      env:
         - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - iptables-dev
            - gcc-6
            - uuid-dev
            - linux-headers-generic
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - iptables-dev
            - gcc-7
            - uuid-dev
            - linux-headers-generic
      env:
        - MATRIX_EVAL="CC=gcc-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - iptables-dev
            - clang-4.0
            - uuid-dev
            - linux-headers-generic
      env:
        - MATRIX_EVAL="CC=clang-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - iptables-dev
            - clang-5.0
            - uuid-dev
            - linux-headers-generic
      env:
        - MATRIX_EVAL="CC=clang-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
language: c
dist: xenial
sudo: required
script:
  - export PATH="$PATH:${BUILD_PREFIX}/bin"
  - $CC --version
  - ./bootstrap.sh
  - ./configure
  - make
