matrix:
  include:
    - os: linux
      install:
        - sudo apt-get install -y gcc-5
      env:
         - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      install:
        - sudo apt-get install -y gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -qq
        - sudo apt-get update -qq
        - sudo apt-get install -y gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"
    - os: linux
      install:
        - sudo apt-get install -y clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"
    - os: linux
      install:
        - sudo apt-get install -y clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y iptables-dev uuid-dev
  - eval "${MATRIX_EVAL}"
language: c
dist: xenial
sudo: required
script:
  - export PATH="$PATH:${BUILD_PREFIX}/bin"
  - $CC --version
  - ./bootstrap.sh
  - ./configure
  - make
